aula/apps/matricula/urls.py
from django.urls import path

from aula.apps.matricula.views import (
    ActivaMatricula,
    Confirma,
    LlistaMatConf,
    LlistaMatFinals,
    OmpleDades,
    ResumConfirmacions,
    VerificaConfirma,
    blanc,
    changeEstat,
    condicions,
    matDobleview,
)

app_name = "matricula"

urlpatterns = [
    path(
        "confirma/<int:nany>/", Confirma, name="relacio_families__matricula__confirma"
    ),
    path("resum/", ResumConfirmacions, name="gestio__matricula__resum"),
    path("escollir/", matDobleview, name="relacio_families__matricula__escollir"),
    path("dades/", OmpleDades, name="relacio_families__matricula__dades"),
    path("activa/", ActivaMatricula, name="gestio__matricula__activa"),
    path("matricula/", LlistaMatConf, name="gestio__matricula__llistat"),
    path(
        "matricula/<int:curs>/<int:nany>/<tipus>/",
        LlistaMatFinals,
        name="gestio__matricula__llistat",
    ),
    path(
        "matricula/<int:pk>/<int:curs>/<int:nany>/<tipus>/",
        VerificaConfirma,
        name="gestio__matricula__llistat",
    ),
    path("changeestat/<int:pk>/<tipus>/", changeEstat, name="changeestat"),
    path("condicions/", condicions, name="varis__condicions__matricula"),
    path("blanc/", blanc, name="gestio__matricula__blanc"),
]

aula/urls.py
# This Python file uses the following encoding: utf-8
import os.path

import private_storage.urls
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeView
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.views.static import serve
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from aula.apps.alumnes.views import (
    llistaGrupsPromocionar,
    mostraGrupPromocionar,
    nouAlumnePromocionar,
)
from aula.utils.views import keepalive, logout_page, menu

admin.autodiscover()
admin.site.enable_nav_sidebar = False


site_media_site_css = os.path.join(os.path.dirname(__file__), "site-css")
site_media_web_demo = os.path.join(os.path.dirname(__file__), "../demo/static-web/demo")

urlpatterns = [
    re_path(
        r"^api-token-auth/", TokenObtainPairView.as_view(), name="token_obtain_pair"
    ),
    re_path(r"^api-token-refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    re_path(r"^api-token-verify/", TokenVerifyView.as_view(), name="token_verify"),
    re_path(r"^keepalive$", keepalive, name="blanc__blanc__keepalive"),
    path("select2/", include("django_select2.urls")),
    re_path(r"^menu/$", menu),
    # (r'^$', 'missatgeria.views.elMeuMur'),
    # (r'^$', 'presencia.views.mostraImpartir'),
    re_path(r"^$", menu, name="blanc__blanc__blanc"),
    re_path(r"^alumnes/", include("aula.apps.alumnes.urls")),
    # (r'^horaris/', include('horaris.urls')),
    re_path(r"^extKronowin/", include("aula.apps.extKronowin.urls")),
    re_path(r"^extSaga/", include("aula.apps.extSaga.urls")),
    re_path(r"^extEsfera/", include("aula.apps.extEsfera.urls")),
    re_path(
        r"^promocions/(?P<grup>\d+)/$",
        mostraGrupPromocionar,
        name="administracio__promocions__grups",
    ),
    re_path(
        r"^promocions/nou-alumne",
        nouAlumnePromocionar,
        name="administracio__alumnes__noualumne",
    ),
    re_path(
        r"^promocions/",
        llistaGrupsPromocionar,
        name="administracio__promocions__llista",
    ),
    re_path(
        r"^presencia/",
        include(
            "aula.apps.presencia.urls",
        ),
    ),
    re_path(r"^incidencies/", include("aula.apps.incidencies.urls")),
    re_path(r"^missatgeria/", include("aula.apps.missatgeria.urls")),
    re_path(r"^usuaris/", include("aula.apps.usuaris.urls")),
    re_path(r"^utils/", include("aula.utils.urls")),
    re_path(r"^tutoria/", include("aula.apps.tutoria.urls")),
    re_path(r"^avaluacioQualitativa/", include("aula.apps.avaluacioQualitativa.urls")),
    re_path(r"^todo/", include("aula.apps.todo.urls")),
    re_path(r"^sortides/", include("aula.apps.sortides.urls")),
    re_path(r"^baixes/", include("aula.apps.baixes.urls")),
    re_path(r"^open/", include("aula.apps.relacioFamilies.urls")),
    re_path(r"^aules/", include("aula.apps.aules.urls")),
    re_path(r"^recursos/", include("aula.apps.material.urls")),
    re_path(r"^presenciaSetmanal/", include("aula.apps.presenciaSetmanal.urls")),
    re_path(r"^extUntis/", include("aula.apps.extUntis.urls")),
    re_path(r"^matricula/", include("aula.apps.matricula.urls", namespace="matricula")),
    re_path(r"^extPreinscripcio/", include("aula.apps.extPreinscripcio.urls")),
    re_path(r"^api/token/", include("aula.mblapp.urls")),
    re_path(r"^api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    # Uncomment the next line to enable the admin:
    re_path(
        r"^admin/login/",
        RedirectView.as_view(url=settings.LOGIN_URL, permanent=True, query_string=True),
    ),
    path("admin/", admin.site.urls),
    # Login i logout automàtics
    # (r'^login/$', 'django.contrib.auth.views.login'),
    re_path(
        r"^password_change/$",
        PasswordChangeView.as_view(),
        {"post_change_redirect": "/"},
        name="password_change",
    ),
    re_path(r"^logout/$", logout_page),
    # fitxers estàtics:
    re_path(r"^site-css/(?P<path>.*)$", serve, {"document_root": site_media_site_css}),
    re_path(r"^error500$", TemplateView.as_view(template_name="500.html")),
    re_path("^private-media/", include(private_storage.urls)),
]


try:
    urlpatterns_custom = [
        re_path(r"^customising/", include("customising.urls")),
    ]
    urlpatterns += urlpatterns_custom
except:  # noqa: E722
    pass

aula/apps/matricula/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_delete
from private_storage.fields import PrivateFileField

from aula.apps.alumnes.models import Alumne, Curs
from aula.apps.extPreinscripcio.models import Preinscripcio
from aula.apps.matricula.business_rules.document import document_post_delete
from aula.apps.sortides.models import Quota, QuotaPagament, return_any_actual


class Matricula(models.Model):
    ESTAT_CHOICES = [
        ("A", "Acceptada"),
        ("F", "Finalitzada"),
    ]
    BONIF_CHOICES = [
        ("0", "Cap"),
        ("5", "50%"),
        ("1", "100%"),
    ]
    CONF_CHOICES = [("C", "Confirma matrícula"), ("N", "No confirma")]

    idAlumne = models.CharField("RALC de l'alumne", max_length=15)
    estat = models.CharField(max_length=1, choices=ESTAT_CHOICES, default="A")
    any = models.IntegerField(default=return_any_actual)
    curs = models.ForeignKey(
        Curs, verbose_name="Curs on matricular-se", on_delete=models.PROTECT
    )
    quota = models.ForeignKey(Quota, on_delete=models.PROTECT, null=True, blank=True)
    alumne = models.ForeignKey(
        Alumne,
        related_name="matricula",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
    )
    preinscripcio = models.ForeignKey(
        Preinscripcio, on_delete=models.PROTECT, null=True, blank=True
    )
    acceptar_condicions = models.BooleanField("Accepto condicions de matrícula")
    acceptacio_en = models.DateTimeField(null=True)
    confirma_matricula = models.CharField(
        "Confirmo matrícula", max_length=1, choices=CONF_CHOICES, null=True, blank=True
    )
    curs_complet = models.BooleanField(
        "Matrícula del curs complet",
        help_text="Matrícula típica de totes les UFs",
        default=False,
    )
    quantitat_ufs = models.IntegerField(
        "UFs soltes, curs no complet", null=True, blank=True, default=0
    )
    llistaufs = models.CharField(
        "Mòduls i ufs de la matrícula",
        help_text="En cas d'UFs soltes",
        max_length=250,
        null=True,
        blank=True,
    )
    bonificacio = models.CharField(
        "Tipus de bonificació taxes", max_length=1, choices=BONIF_CHOICES, default="0"
    )
    fracciona_taxes = models.BooleanField("Fracciona pagament taxes", default=False)
    nom = models.CharField("Nom alumne", max_length=50, default="")
    cognoms = models.CharField("Cognoms alumne", max_length=100, default="")
    centre_de_procedencia = models.CharField(
        "Centre de procedència", max_length=50, null=True, blank=True
    )
    data_naixement = models.DateField("Data de naixement", default=None)
    alumne_correu = models.EmailField(
        "Correu de l'alumne", help_text="Correu de notificacions de l'alumne", null=True
    )
    adreca = models.CharField("Adreça", max_length=250, default="", blank=True)
    localitat = models.CharField("Localitat", max_length=240, default="", blank=True)
    cp = models.CharField("Codi postal", max_length=10, default="", blank=True)
    rp1_dni = models.CharField("Dni", max_length=10, default="", blank=True)
    rp1_nom = models.CharField(
        "Nom", max_length=50, default="", blank=True
    )  # responsable 1
    rp1_cognoms = models.CharField("Cognoms", max_length=100, default="", blank=True)
    rp1_telefon = models.CharField("Telèfon", max_length=15, default="", blank=True)
    rp1_correu = models.EmailField("Correu", default="", blank=True)
    rp1_parentiu = models.CharField("Parentiu", max_length=20, blank=True)
    rp1_localitat = models.CharField("Localitat", max_length=240, blank=True)
    rp1_cp = models.CharField("Codi postal", max_length=10, blank=True)
    rp1_adreca = models.CharField("Adreça", max_length=250, blank=True)
    rp2_dni = models.CharField("Dni", max_length=10, null=True, blank=True)
    rp2_nom = models.CharField(
        "Nom", max_length=50, null=True, blank=True
    )  # responsable 2
    rp2_cognoms = models.CharField("Cognoms", max_length=100, null=True, blank=True)
    rp2_telefon = models.CharField("Telèfon", max_length=15, null=True, blank=True)
    rp2_correu = models.EmailField("Correu", null=True, blank=True)
    rp2_parentiu = models.CharField("Parentiu", max_length=20, null=True, blank=True)
    rp2_localitat = models.CharField("Localitat", max_length=240, null=True, blank=True)
    rp2_cp = models.CharField("Codi postal", max_length=10, null=True, blank=True)
    rp2_adreca = models.CharField("Adreça", max_length=250, null=True, blank=True)

    class Meta:
        verbose_name = "Matrícula"
        verbose_name_plural = "Matrícules"

    def __str__(self):
        return str(self.alumne) + " " + str(self.any) + " " + str(self.curs)

    @property
    def pagamentFet(self):
        pag = self.getPagament
        if pag:
            for p in pag:
                if not p.pagamentFet:
                    return False
            return True
        return False

    @property
    def getPagament(self):
        p = QuotaPagament.objects.filter(
            alumne=self.alumne,
            quota__any=self.any,
            quota__tipus__nom=settings.CUSTOM_TIPUS_QUOTA_MATRICULA,
        )
        return p


class Document(models.Model):
    fitxer = PrivateFileField(
        "Fitxer amb documents",
        upload_to="matricula/%Y/",
        max_file_size=settings.FILE_UPLOAD_MAX_MEMORY_SIZE,
        null=True,
    )
    matricula = models.ForeignKey(
        Matricula, on_delete=models.PROTECT, blank=True, null=True
    )

    class Meta:
        verbose_name = "Document"
        verbose_name_plural = "Documents"

    def __str__(self):
        return str(self.fitxer.name) + (
            (" " + str(self.matricula)) if self.matricula else ""
        )


post_delete.connect(document_post_delete, sender=Document)

aula/apps/matricula/templates/confirma_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ titol }}</h2>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_ul }}
	<a href="{{ view.get_success_url }}" class="btn btn-secondary">Següent</a>
    <input class="btn btn-primary" type="submit" value="Grava" />
</form>
{% endblock %}

aula/apps/matricula/templates/confirma_form.html
{% extends 'base.html' %}

{% block content %}
<h3>Confirmació de matrícula</h3>
<form method="post">{% csrf_token %}
Benvolguda família,<br>
<br>
Com ja sabeu el curs ja s’està acabant i cal preparar el nou curs, per això us demanem que confirmeu la plaça si voleu continuar amb nosaltres.<br>
Si el vostre fill/a continua en el centre <b>comproveu que les dades personals siguin correctes</b> i feu click al botó <b>Envia</b>.<br>
És molt important tenir els telèfons i correus electrònics actualitzats per facilitar el contacte amb vosaltres.<br>
<br>
Aprofitem l’avinentesa per a saludar-vos cordialment.<br>
La direcció<br><br>

 		{% for field in form.visible_fields %}
        <div class="row row-padded" style="background-color:{% cycle '#f5f5f5' 'white' %}">
	        <div class="col-sm-8 col-xs-12 tria_tag">
		        {% if field.errors %}		        	
			        <div class="alert alert-danger">
			        <button type="button" class="close" data-dismiss="alert">&times;</button>
				        <ul>
				          {% for error in field.errors%}
				          <li>{{ error }}</li>
			              {% endfor %}
			            </ul>
		         	</div>
		        {% endif %}
	        </div>
        </div>
        {% endfor %}


    <p><b>Curs actual: </b>{{ curs }}</p>
    {{ form.as_p }}
	He llegit i accepto les <a target = _blank href="{% url  'matricula:varis__condicions__matricula' %}">condicions de matrícula</a>
    <br><br>
    <input class="btn btn-primary" type="submit" value="Envia" />
    <br><br><br><br>
</form>

{{ rgpd|safe }}<br>

{% endblock %}

aula/apps/matricula/templates/dades_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

            <p>{{ dades.peticio.idAlumne }}</p>
            <p>{{ dades.cognoms }}, {{ dades.nom }}</p>
            <p>{{ dades.peticio.curs }}</p>
            <p>{{ dades.rp1_nom }}</p>
            <p>{{ dades.rp1_telefon }}</p>
            <p>{{ dades.peticio.email }}</p>
            <p>
            {%if dades.acceptar_condicions %}
               <b>Condicions acceptades</b>
            {%else%}
               <b style="color:Tomato;">Falta acceptació</b>
            {%endif%}
            </p>
            <p>
            {%if dades.getPagament %}
	            {%if dades.pagamentFet %}
	               <b>Pagament Fet</b>
	            {%else%}
	               <b style="color:Tomato;">Pagament pendent</b>
	            {%endif%}
            {%endif%}
            </p>
            <p><a href="{{ dades.files.url }}" target="_blank">Fitxer</a></p>
			
			<a href="{% url "matricula:gestio__confirma__matricula" %}">Tornar</a>

 
 {% endblock %}

aula/apps/matricula/templates/dades_form.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

{% block content %}
<h2>{{ titol }}</h2>
<p>Pàg. {{ wizard.steps.step1 }} de {{ wizard.steps.count }}</p>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
	<table>
	{{ wizard.management_form }}
	{% if wizard.form.forms %}
	    {{ wizard.form.management_form }}
	    {% for form in wizard.form.forms %}
	        {{ form }}
	    {% endfor %}
	{% else %}
	    {{ wizard.form }}
	{% endif %}
	</table>
	{% if wizard.steps.step1 == wizard.steps.count %}
		<b>He llegit i accepto les</b> <a target = _blank href="{% url  'matricula:varis__condicions__matricula' %}">condicions de matrícula</a>
		<br><br>
	{% endif %}
	{% if wizard.steps.prev %}
	         <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% trans "anterior" %}</button>
	{% endif %}
	{% if wizard.steps.step1 == wizard.steps.count %}
		<input class="btn btn-primary" type="submit" value="{% trans "grava" %}" name="grava"/>
	{% else %}
		<input class="btn btn-primary" type="submit" value="{% trans "continua" %}" name="grava"/>
	{% endif %}
	
</form>

<br><br>{{ rgpd|safe }}

{% endblock %}

aula/apps/matricula/templates/dades_list.html
{% extends "base.html" %}
{% load i18n %}
{% load detalls %}

{% block content %}
<h2>{{ titol }}</h2>
<table style="width:100%">
<lu>
{% for dades in object_list %}
	  <tr>
            <td><li>{{ dades.idAlumne }}&nbsp</li></td>

			<td>
			<a href="{% url "gestio__usuari__cercaresultat" dades.alumne.id 'all' %}" target="_blank">{{ dades.cognoms }}, {{ dades.nom }}&nbsp</a>
            </td>
            
			<td>{{ dades.curs }}({{ dades | torn }})&nbsp</td>
            <td>{{ dades.rp1_telefon }}&nbsp</td>
            <td>{{ dades.rp1_correu }}&nbsp</td>
		    
            {% ctrlPag dades as matmis %}
            {% ctrlTax dades as taxmis %}
            <td>
              {%if matmis.mess %}
                  <b style="color:{{ matmis.color }};">{{ matmis.mess }}</b>
              {%endif%}
              {%if taxmis.mess %}
                  <br>
                  <b style="color:{{ taxmis.color }};">{{ taxmis.mess }}</b>
              {%endif%}
            &nbsp</td>

            {%if dades.bonificacio != '0' and dades.curs.nivell.taxes %}
	            <td><b>Bon.Tax:{{ dades.get_bonificacio_display }}&nbsp</b></td>
	        {%else%}
	            <td></td>
            {%endif%}
			{%if dades|documents %}
                <td>
				{% for d in dades|documents %}
				    <a href="{{ d.fitxer.url }}" target="_blank">Fitxer{{ forloop.counter }}</a>
				{% endfor %}
				</td>         
            {% else %}
                <td></td>
            {% endif %}
	        <td>
            {%if dades.confirma_matricula %}
	            {%if dades.confirma_matricula == 'C' %}
	            	<b>Confirmada&nbsp</b>
	            {% endif %}
	            {%if dades.confirma_matricula == 'N' %}
	            	<b>No Confirma&nbsp</b>
	            {% endif %}
			{% endif %}            
	        </td>
            {%if dades.estat == 'A' and dades.confirma_matricula != 'C' %}
	            <td><a class="btn btn-info pull" 
				    href="{% url "matricula:changeestat" dades.id tipus %}">
				    Finalitza
				</a></td>
			{% else %}
			    {%if dades.estat == 'F' %}
				    <td>Finalitzada</td>
				{% else %}
				    <td><a class="btn btn-info pull" 
				    href="{% url "matricula:gestio__matricula__llistat" dades.id dades.curs.id dades.any 'C' %}">
				    Verifica
				</a></td>
			    {% endif %}
			{% endif %}
		</tr>
		<tr><td colspan="9">
            {%if dades.curs_complet %}
	            <b>Matrícula curs complet</b>&nbsp
            {%else%}
	            {%if dades.quantitat_ufs > 0 %}
	             	<b>Matrícula ufs soltes ({{ dades.quantitat_ufs }}): {{ dades.llistaufs }}</b>&nbsp
	            {%endif%}
            {%endif%}
            </td>
         </tr>
         <tr><td colspan="9">&nbsp</tr>
	{% empty %}
		<li>Sense matrícules pendents</li>
{% endfor %}
</lu>
</table>
{% endblock %}

aula/apps/matricula/templates/file_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

        {{ dat|safe }}

{% endblock %}

aula/apps/matricula/templates/peticio.html
{% extends 'form.html' %}

{% block extrahead %}
<style type="text/css">
  body {
    padding-bottom: 40px;
    background-color: #f5f5f5;
  }
</style>
{% endblock %}

{% block preform %}
  <p class="text-center"><img src="/site-css/logo.png" width="154" heigh="64"></p>
{% endblock %}

aula/apps/matricula/templates/peticio_form.html
{% extends 'base.html' %}

{% block content %}
<h3>Peticions pendents</h3>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
	<a href="{{ view.get_success_url }}" class="btn btn-secondary">Següent</a>
    <input class="btn btn-primary" type="submit" value="Grava" />
</form>
{% endblock %}